name: deploy-ci-cd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale and authenticate
        run: |
          sudo tailscaled &
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
          sleep 5

      - name: Trigger deployment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/work/quoc-bao-internship
            git pull origin master
            git checkout master
